version: "3.9"

services:
  gradex-contracts:
    build:
      context: ./gradex_contracts
      dockerfile: Dockerfile
    container_name: gradex-contracts
    volumes:
      - ./gradex_contracts:/app
      - cargo-cache:/usr/local/cargo/registry

volumes:
  cargo-cache:
